package main

import "fmt"

func handleError(err error) {
	fmt.Println(err)
	return
}
